"""Area seed data, part 1."""

AREAS_1 = [('lingua_italiana',
  [('li_storia', 'Storia della lingua', "Evoluzione storica dell'italiano dal latino ai giorni nostri"),
   ('li_normativa', 'Normativa linguistica', 'Regole, accademie e istituzioni che normano la lingua'),
   ('li_lessico', 'Lessicologia e lessicografia', 'Studio del vocabolario, dei neologismi e dei dizionari'),
   ('li_varieta', 'Varietà linguistiche', 'Dialetti, registri, italiano regionale e socioletti'),
   ('li_ortografia', 'Ortografia e pronuncia', 'Norme di scrittura, accento e fonetica italiana'),
   ('li_uso', 'Uso della lingua', 'Pratiche comunicative, lingua dei media e dei giovani'),
   ('li_italiano_l2', 'Italiano come L2', "Insegnamento e apprendimento dell'italiano per stranieri"),
   ('li_tecniche_scrittura', 'Tecniche di scrittura', 'Stili, generi testuali e strategie di composizione')]),
 ('grammatica_linguistica',
  [('gl_fonologia', 'Fonologia e fonetica', 'Studio dei suoni del linguaggio'),
   ('gl_morfologia', 'Morfologia', 'Formazione delle parole, flessione e derivazione'),
   ('gl_sintassi', 'Sintassi', 'Struttura delle frasi e relazioni tra costituenti'),
   ('gl_semantica', 'Semantica e pragmatica', 'Significato delle espressioni e uso contestuale'),
   ('gl_tipologia', 'Tipologia linguistica', 'Classificazione delle lingue del mondo'),
   ('gl_sociolinguistica', 'Sociolinguistica', 'Rapporto tra lingua e società'),
   ('gl_psicolinguistica', 'Psicolinguistica', 'Processi mentali sottostanti al linguaggio'),
   ('gl_neurolinguistica', 'Neurolinguistica', 'Basi neurali del linguaggio e patologie'),
   ('gl_linguistica_computazionale', 'Linguistica computazionale', 'Elaborazione del linguaggio naturale con metodi informatici'),
   ('gl_stilistica', 'Stilistica e retorica', 'Analisi dello stile e delle figure retoriche')]),
 ('letteratura',
  [('let_italiana', 'Letteratura italiana', 'Opere, autori e movimenti della letteratura in Italia'),
   ('let_europea', 'Letteratura europea', 'Tradizioni letterarie dei principali paesi europei'),
   ('let_mondiale', 'Letteratura mondiale', 'Letterature extraeuropee e letteratura comparata'),
   ('let_poesia', 'Poesia', 'Generi poetici, metrica e movimenti lirici'),
   ('let_narrativa', 'Narrativa', 'Romanzo, racconto, novella e tecniche narrative'),
   ('let_teatro', 'Teatro letterario', 'Drammaturgia e storia del teatro come forma letteraria'),
   ('let_saggistica', 'Saggistica e critica', 'Opere di critica letteraria, teoria e saggistica'),
   ('let_generi', 'Generi letterari', 'Classificazione e caratteristiche dei generi'),
   ('let_orale', 'Tradizione orale', 'Fiabe, leggende e narrazione popolare'),
   ('let_contemporanea', 'Letteratura contemporanea', 'Produzione letteraria dagli anni Ottanta a oggi')]),
 ('storia',
  [('st_antica', 'Storia antica', 'Civiltà del Mediterraneo e del Vicino Oriente fino al V secolo'),
   ('st_medioevo', 'Storia medievale', 'Europa e Mediterraneo dal V al XV secolo'),
   ('st_moderna', 'Storia moderna', 'Età moderna dal XV al XVIII secolo'),
   ('st_contemporanea', 'Storia contemporanea', 'Dalla Rivoluzione francese al presente'),
   ('st_italia', "Storia d'Italia", 'Eventi politici, sociali e culturali della penisola italiana'),
   ('st_metodologia', 'Storiografia e metodologia', 'Teoria della storia, fonti e metodi critici'),
   ('st_economica', 'Storia economica', 'Evoluzione dei sistemi economici e del lavoro'),
   ('st_sociale', 'Storia sociale', 'Vita quotidiana, classi e stratificazione nel tempo'),
   ('st_culturale', 'Storia culturale', 'Mentalità, rappresentazioni e pratiche simboliche'),
   ('st_militare', 'Storia militare', 'Guerre, strategie e tecnologie belliche')]),
 ('geografia',
  [('geo_fisica', 'Geografia fisica', 'Rilievi, climi, idrografia e ecosistemi terrestri'),
   ('geo_umana', 'Geografia umana', 'Popolazione, insediamenti e attività antropiche'),
   ('geo_politica', 'Geografia politica', 'Confini, Stati e organizzazione territoriale'),
   ('geo_economica', 'Geografia economica', 'Distribuzione delle risorse e dei settori produttivi'),
   ('geo_regionale', 'Geografia regionale', 'Studio delle aree geografiche del mondo'),
   ('geo_italia', "Geografia dell'Italia", 'Territorio, regioni e caratteristiche della penisola'),
   ('geo_europa', "Geografia dell'Europa", 'Caratteristiche fisiche e umane del continente europeo'),
   ('geo_cartografia', 'Cartografia e GIS', 'Tecniche di rappresentazione e sistemi informativi geografici'),
   ('geo_ambientale', 'Geografia ambientale', 'Rapporto tra ambiente e sviluppo sostenibile'),
   ('geo_urbana', 'Geografia urbana', 'Città, metropolitanizzazione e pianificazione')]),
 ('matematica',
  [('mat_aritmetica', 'Aritmetica', 'Numeri, operazioni e proprietà fondamentali'),
   ('mat_algebra', 'Algebra', 'Strutture algebriche, equazioni e polinomi'),
   ('mat_geometria', 'Geometria', 'Studio delle forme, spazi e trasformazioni'),
   ('mat_analisi', 'Analisi matematica', 'Calcolo differenziale, integrale e successioni'),
   ('mat_probabilita', 'Calcolo delle probabilità', 'Teoria assiomatica e distribuzioni'),
   ('mat_statistica_matematica', 'Statistica matematica', "Inferenza, stima e test d'ipotesi"),
   ('mat_logica_matematica', 'Logica matematica', 'Sistemi formali, dimostrazioni e teoria dei modelli'),
   ('mat_storia', 'Storia della matematica', 'Evoluzione del pensiero matematico nelle civiltà'),
   ('mat_matematica_applicata', 'Matematica applicata', 'Modelli matematici per scienze e ingegneria'),
   ('mat_teoria_numeri', 'Teoria dei numeri', 'Proprietà degli interi e strutture aritmetiche')]),
 ('logica',
  [('log_formale', 'Logica formale', 'Sistemi deduttivi, sintassi e semantica'),
   ('log_proposizionale', 'Logica proposizionale', 'Calcolo dei connettivi e delle tautologie'),
   ('log_predicativa', 'Logica predicativa', 'Quantificatori, predicati e strutture del primo ordine'),
   ('log_modale', 'Logica modale', 'Necessità, possibilità e mondi possibili'),
   ('log_filosofica', 'Logica filosofica', 'Fondamenti, paradossi e teorie del ragionamento'),
   ('log_informatica', "Logica per l'informatica", 'Programmazione logica, verifica e dimostrazione automatica'),
   ('log_argomentazione', "Teoria dell'argomentazione", 'Schemi inferenziali e fallacie'),
   ('log_decisione', 'Teoria della decisione', 'Scelta razionale sotto incertezza')]),
 ('statistica_probabilita',
  [('sp_descrittiva', 'Statistica descrittiva', 'Rappresentazione e sintesi dei dati'),
   ('sp_inferenziale', 'Statistica inferenziale', 'Stima, intervalli di confidenza e test'),
   ('sp_probabilita', 'Teoria della probabilità', 'Assiomi, variabili casuali e teoremi limite'),
   ('sp_modelli', 'Modelli statistici', 'Regressione, ANOVA e modelli lineari'),
   ('sp_campionamento', 'Tecniche di campionamento', 'Metodi per selezionare sottoinsiemi rappresentativi'),
   ('sp_dati', 'Analisi dei dati', 'Esplorazione, pulizia e preparazione dei dataset'),
   ('sp_bayesiana', 'Statistica bayesiana', 'Approccio basato sul teorema di Bayes'),
   ('sp_sperimentali', 'Progetti sperimentali', 'Design degli esperimenti e controllo delle variabili'),
   ('sp_applicazioni', 'Applicazioni pratiche', 'Sondaggi, demografia e ricerca di mercato')]),
 ('fisica',
  [('fis_meccanica', 'Meccanica classica', 'Cinematica, dinamica, statica e fluidi'),
   ('fis_termodinamica', 'Termodinamica', 'Calore, lavoro, entropia e macchine termiche'),
   ('fis_elettromagnetismo', 'Elettromagnetismo', 'Elettricità, magnetismo e onde elettromagnetiche'),
   ('fis_ottica', 'Ottica', 'Luce, lenti, interferenza e diffrazione'),
   ('fis_relativita', 'Relatività', 'Teorie ristretta e generale di Einstein'),
   ('fis_quantistica', 'Meccanica quantistica', 'Dualismo onda-particella, principio di indeterminazione'),
   ('fis_nucleare', 'Fisica nucleare', 'Nucleo atomico, radioattività e reazioni nucleari'),
   ('fis_particelle', 'Fisica delle particelle', 'Quark, leptoni, bosoni e interazioni fondamentali'),
   ('fis_astrofisica', 'Astrofisica', 'Fisica applicata agli oggetti celesti'),
   ('fis_storia', 'Storia della fisica', 'Evoluzione delle teorie fisiche e dei grandi esperimenti')]),
 ('chimica',
  [('chim_generale', 'Chimica generale', 'Struttura atomica, legami e stechiometria'),
   ('chim_organica', 'Chimica organica', 'Composti del carbonio, reazioni e sintesi'),
   ('chim_inorganica', 'Chimica inorganica', 'Composti minerali, metalli e non metalli'),
   ('chim_analitica', 'Chimica analitica', 'Metodi di identificazione e quantificazione'),
   ('chim_fisica', 'Chimica fisica', 'Termodinamica, cinetica e spettroscopia'),
   ('chim_biochimica', 'Biochimica', 'Processi chimici nei sistemi viventi'),
   ('chim_ambientale', 'Chimica ambientale', 'Inquinanti, cicli biogeochimici e sostenibilità'),
   ('chim_materiali', 'Scienza dei materiali', 'Proprietà e applicazioni dei materiali'),
   ('chim_industriale', 'Chimica industriale', 'Processi produttivi e ingegneria chimica'),
   ('chim_storia', 'Storia della chimica', "Dall'alchimia alla chimica moderna")])]
