"""Area seed data, part 2."""

AREAS_2 = [('biologia',
  [('bio_botanica', 'Botanica', 'Studio delle piante e dei loro processi vitali'),
   ('bio_zoologia', 'Zoologia', 'Studio degli animali, tassonomia e comportamento'),
   ('bio_genetica', 'Genetica', 'Ereditarietà, DNA, genomi e ingegneria genetica'),
   ('bio_microbiologia', 'Microbiologia', 'Batteri, virus, funghi e microrganismi'),
   ('bio_ecologia', 'Ecologia biologica', 'Interazioni tra organismi e ambiente'),
   ('bio_evolution', 'Evoluzione', 'Teoria darwiniana, speciazione e filogenesi'),
   ('bio_cellulare', 'Biologia cellulare', 'Struttura e funzione della cellula'),
   ('bio_molecolare', 'Biologia molecolare', 'Processi molecolari della replicazione e espressione genica'),
   ('bio_fisiologia', 'Fisiologia', 'Funzioni degli organismi e dei loro apparati'),
   ('bio_antropologia', 'Antropologia biologica', 'Evoluzione umana e biodiversità')]),
 ('medicina_salute',
  [('med_anatomia', 'Anatomia', 'Struttura del corpo umano'),
   ('med_fisiologia', 'Fisiologia umana', 'Funzioni degli apparati e degli organi'),
   ('med_patologia', 'Patologia', 'Studio delle malattie e delle loro cause'),
   ('med_farmacologia', 'Farmacologia', "Farmaci, meccanismi d'azione e terapie"),
   ('med_chirurgia', 'Chirurgia', 'Tecniche operatorie e specialità chirurgiche'),
   ('med_psichiatria', 'Psichiatria e salute mentale', 'Disturbi psichici e trattamenti'),
   ('med_pediatria', 'Pediatria', "Medicina dell'infanzia e dell'adolescenza"),
   ('med_prevenzione', 'Medicina preventiva', 'Igiene, vaccini e promozione della salute'),
   ('med_nutrizione', 'Nutrizione clinica', 'Dieta, metabolismo e patologie nutrizionali'),
   ('med_emergenza', "Medicina d'emergenza", 'Pronto soccorso, rianimazione e trauma')]),
 ('astronomia',
  [('astro_sistema_solare', 'Sistema solare', 'Pianeti, satelliti, asteroidi e comete'),
   ('astro_stelle', 'Stelle ed evoluzione stellare', 'Nascita, vita e morte delle stelle'),
   ('astro_galassie', 'Galassie e cosmologia', "Struttura dell'universo e modelli cosmologici"),
   ('astro_osservazione', 'Osservazione astronomica', 'Strumenti, tecniche e cataloghi celesti'),
   ('astro_esopianeti', 'Esopianeti', 'Pianeti extrasolari e ricerca di vita'),
   ('astro_radio', 'Radioastronomia', 'Studio delle onde radio cosmiche'),
   ('astro_storia', "Storia dell'astronomia", "Dall'antichità all'astronomia moderna"),
   ('astro_astronautica', 'Astronautica', "Tecnologie per l'esplorazione spaziale")]),
 ('scienze_terra',
  [('st_geologia', 'Geologia', 'Studio della litosfera, rocce e minerali'),
   ('st_vulcanologia', 'Vulcanologia', 'Vulcani, magma ed eruzioni'),
   ('st_sismologia', 'Sismologia', 'Terremoti, onde sismiche e rischio sismico'),
   ('st_paleontologia', 'Paleontologia', 'Fossili ed evoluzione della vita sulla Terra'),
   ('st_idrogeologia', 'Idrogeologia', 'Acque sotterranee e loro dinamica'),
   ('st_oceanografia', 'Oceanografia', 'Studio degli oceani e dei loro fenomeni'),
   ('st_climatologia', 'Climatologia', 'Climi del passato e del presente'),
   ('st_geochimica', 'Geochimica', 'Composizione chimica della Terra'),
   ('st_geofisica', 'Geofisica', 'Fisica della Terra e dei suoi campi'),
   ('st_cartografia_geologica', 'Cartografia geologica', 'Rappresentazione del sottosuolo')]),
 ('ambiente_ecologia',
  [('amb_ecosistemi', 'Ecosistemi', 'Comunità biotiche e abiotiche e loro dinamiche'),
   ('amb_biodiversita', 'Biodiversità', 'Variabilità della vita a tutti i livelli'),
   ('amb_cambiamento_climatico', 'Cambiamento climatico', 'Riscaldamento globale e sue conseguenze'),
   ('amb_inquinamento', 'Inquinamento', "Contaminazione dell'aria, acqua e suolo"),
   ('amb_sostenibilita', 'Sviluppo sostenibile', 'Modelli di sviluppo a basso impatto ambientale'),
   ('amb_energie_rinnovabili', 'Energie rinnovabili', 'Fonti energetiche alternative e pulite'),
   ('amb_gestione_risorse', 'Gestione delle risorse naturali', 'Acqua, suolo, foreste e pesca'),
   ('amb_urbanistica_verde', 'Urbanistica verde', 'Città sostenibili e infrastrutture verdi'),
   ('amb_educazione_ambientale', 'Educazione ambientale', 'Sensibilizzazione e comportamenti eco-sostenibili'),
   ('amb_politiche', 'Politiche ambientali', 'Normative, accordi internazionali e governance')]),
 ('informatica',
  [('info_algoritmi', 'Algoritmi e strutture dati', 'Progettazione e analisi di algoritmi'),
   ('info_programmazione', 'Programmazione', 'Linguaggi, paradigmi e tecniche di codifica'),
   ('info_software', 'Ingegneria del software', 'Progettazione, sviluppo e manutenzione di sistemi'),
   ('info_architetture', 'Architetture dei calcolatori', 'Hardware, processori e memorie'),
   ('info_sistemi_operativi', 'Sistemi operativi', 'Gestione delle risorse di un computer'),
   ('info_reti', 'Reti di calcolatori', 'Protocolli, Internet e comunicazione dati'),
   ('info_sicurezza_informatica', 'Sicurezza informatica', 'Crittografia, minacce e difesa dei sistemi'),
   ('info_basi_dati', 'Basi di dati', 'Progettazione e gestione dei database'),
   ('info_grafica', 'Grafica computazionale', 'Visualizzazione, rendering e realtà virtuale'),
   ('info_storia', "Storia dell'informatica", 'Evoluzione dei computer e del software')]),
 ('intelligenza_artificiale',
  [('ia_apprendimento', 'Apprendimento automatico', 'Algoritmi che apprendono dai dati'),
   ('ia_deep_learning', 'Deep learning', 'Reti neurali profonde e rappresentazioni gerarchiche'),
   ('ia_nlp', 'Elaborazione del linguaggio naturale', 'Comprensione e generazione del linguaggio'),
   ('ia_visione', 'Visione artificiale', 'Riconoscimento e interpretazione di immagini e video'),
   ('ia_ragionamento', 'Ragionamento automatico', 'Sistemi esperti, pianificazione e logica'),
   ('ia_robotica', 'Robotica intelligente', 'Agenti autonomi, sensori e attuatori'),
   ('ia_etica_ia', "Etica dell'IA", 'Bias, responsabilità e impatto sociale'),
   ('ia_generativa', 'IA generativa', 'Modelli per la creazione di contenuti'),
   ('ia_multimodale', 'Intelligenza multimodale', 'Fusione di testo, immagine, audio e video'),
   ('ia_storia', "Storia dell'IA", 'Dalle origini simboliche ai modelli fondazionali')]),
 ('ingegneria',
  [('ing_civile', 'Ingegneria civile', 'Progettazione di infrastrutture e costruzioni'),
   ('ing_meccanica', 'Ingegneria meccanica', 'Macchine, meccanismi e sistemi energetici'),
   ('ing_elettrica', 'Ingegneria elettrica', "Produzione, trasmissione e utilizzo dell'energia elettrica"),
   ('ing_elettronica', 'Ingegneria elettronica', 'Circuiti, semiconduttori e sistemi embedded'),
   ('ing_informatica', 'Ingegneria informatica', 'Sistemi hardware-software integrati'),
   ('ing_chimica', 'Ingegneria chimica', 'Processi industriali e reattori'),
   ('ing_aerospaziale', 'Ingegneria aerospaziale', 'Aeromobili, veicoli spaziali e propulsione'),
   ('ing_biomedica', 'Ingegneria biomedica', 'Dispositivi medici e sistemi per la salute'),
   ('ing_ambientale', 'Ingegneria ambientale', 'Tecnologie per la protezione ambientale'),
   ('ing_gestionale', 'Ingegneria gestionale', 'Organizzazione, logistica e ottimizzazione')]),
 ('tecnologia',
  [('tec_telecomunicazioni', 'Telecomunicazioni', 'Tecnologie per la trasmissione a distanza'),
   ('tec_nanotecnologie', 'Nanotecnologie', 'Manipolazione della materia a scala nanometrica'),
   ('tec_biotecnologie', 'Biotecnologie', 'Applicazione tecnologica ai sistemi biologici'),
   ('tec_materiali_avanzati', 'Materiali avanzati', 'Grafene, metamateriali e leghe innovative'),
   ('tec_stampa_3d', 'Stampa 3D', 'Tecniche di manifattura additiva'),
   ('tec_quantistica', 'Tecnologie quantistiche', 'Computer, sensori e comunicazione quantistica'),
   ('tec_industria_4', 'Industria 4.0', 'Automazione, IoT e fabbriche intelligenti'),
   ('tec_wearable', 'Dispositivi indossabili', 'Smartwatch, sensori biometrici e realtà aumentata'),
   ('tec_droni', 'Droni e veicoli autonomi', 'Robotica aerea e guida autonoma'),
   ('tec_blocchi', 'Tecnologia blockchain', 'Registri distribuiti e smart contract')]),
 ('economia',
  [('eco_micro', 'Microeconomia', 'Comportamento di consumatori, imprese e mercati'),
   ('eco_macro', 'Macroeconomia', 'Aggregati economici, PIL, inflazione e disoccupazione'),
   ('eco_storia', 'Storia economica', 'Evoluzione dei sistemi economici nel tempo'),
   ('eco_sviluppo', 'Economia dello sviluppo', 'Crescita, povertà e disuguaglianze'),
   ('eco_internazionale', 'Economia internazionale', 'Commercio, cambi e integrazione globale'),
   ('eco_lavoro', 'Economia del lavoro', 'Mercato del lavoro, salari e politiche occupazionali'),
   ('eco_pubblica', 'Economia pubblica', 'Spesa, tassazione e beni pubblici'),
   ('eco_ambientale', 'Economia ambientale', 'Esternalità, valutazione e politiche verdi'),
   ('eco_comportamentale', 'Economia comportamentale', 'Psicologia applicata alle scelte economiche'),
   ('eco_monetaria', 'Economia monetaria', 'Banche centrali, politiche monetarie e liquidità')])]
