"""Generated seed data for the Italian Knowledge Graph."""

MACROAREAS = [('lingua_italiana',
  'Lingua italiana',
  'Storia, normativa, uso e varietà della lingua italiana'),
 ('grammatica_linguistica',
  'Grammatica e linguistica',
  'Studio scientifico del linguaggio e delle sue strutture'),
 ('letteratura', 'Letteratura', 'Produzione letteraria italiana e mondiale'),
 ('storia', 'Storia', 'Studio del passato umano attraverso fonti e interpretazioni'),
 ('geografia', 'Geografia', 'Studio della Terra, dei suoi abitanti e dei fenomeni spaziali'),
 ('matematica',
  'Matematica',
  'Studio dei numeri, delle strutture, degli spazi e dei cambiamenti'),
 ('logica', 'Logica', 'Studio del ragionamento valido e delle inferenze'),
 ('statistica_probabilita',
  'Statistica e probabilità',
  'Raccolta, analisi dei dati e studio degli eventi casuali'),
 ('fisica', 'Fisica', "Studio della materia, dell'energia e delle loro interazioni"),
 ('chimica', 'Chimica', 'Studio della composizione, struttura e trasformazione della materia'),
 ('biologia', 'Biologia', 'Studio degli organismi viventi e dei processi vitali'),
 ('medicina_salute',
  'Medicina e salute',
  "Scienza della cura, prevenzione e benessere dell'organismo umano"),
 ('astronomia', 'Astronomia', "Studio degli oggetti celesti e dell'universo"),
 ('scienze_terra',
  'Scienze della Terra',
  'Studio della litosfera, idrosfera, atmosfera e loro dinamiche'),
 ('ambiente_ecologia',
  'Ambiente ed ecologia',
  'Rapporti tra organismi e ambiente, sostenibilità e conservazione'),
 ('informatica',
  'Informatica',
  "Studio teorico e pratico dell'elaborazione automatica dell'informazione"),
 ('intelligenza_artificiale',
  'Intelligenza artificiale',
  "Sistemi computazionali in grado di simulare l'intelligenza umana"),
 ('ingegneria',
  'Ingegneria',
  'Applicazione delle scienze esatte alla progettazione e costruzione'),
 ('tecnologia', 'Tecnologia', 'Strumenti, tecniche e processi per risolvere problemi pratici'),
 ('economia',
  'Economia',
  'Studio della produzione, distribuzione e consumo di beni e servizi'),
 ('finanza', 'Finanza', 'Gestione del capitale, degli investimenti e dei mercati monetari'),
 ('diritto', 'Diritto', 'Sistema di norme che regolano la convivenza umana'),
 ('politica_istituzioni',
  'Politica e istituzioni',
  'Organizzazione del potere, governo e amministrazione pubblica'),
 ('filosofia',
  'Filosofia',
  "Indagine critica sui fondamenti del sapere, dell'essere e dell'agire"),
 ('etica', 'Etica', 'Studio dei principi morali e della condotta umana'),
 ('psicologia',
  'Psicologia',
  'Studio scientifico del comportamento e dei processi mentali'),
 ('sociologia',
  'Sociologia',
  'Studio delle strutture sociali e delle dinamiche collettive'),
 ('antropologia',
  'Antropologia',
  "Studio dell'uomo in tutte le sue dimensioni biologiche e culturali"),
 ('religioni', 'Religioni', 'Sistemi di credenze, pratiche rituali e fenomeni religiosi'),
 ('arte', 'Arte', 'Espressione creativa attraverso forme visive e concettuali'),
 ('musica', 'Musica', "Arte dell'organizzazione dei suoni nel tempo"),
 ('cinema_spettacolo',
  'Cinema e spettacolo',
  'Arti sceniche, cinematografiche e dello spettacolo dal vivo'),
 ('architettura',
  'Architettura',
  'Arte e tecnica di progettare e costruire spazi abitati'),
 ('comunicazione', 'Comunicazione', 'Processi di trasmissione e scambio di informazioni'),
 ('educazione',
  'Educazione',
  'Processi di formazione, istruzione e sviluppo delle persone'),
 ('lavoro_professioni',
  'Lavoro e professioni',
  'Attività lavorative, mercato del lavoro e figure professionali'),
 ('industria_manifattura',
  'Industria e manifattura',
  'Trasformazione industriale delle materie prime in prodotti'),
 ('agricoltura',
  'Agricoltura',
  'Coltivazione del suolo, allevamento e produzione agroalimentare'),
 ('energia', 'Energia', 'Fonti, produzione, distribuzione e consumo di energia'),
 ('trasporti',
  'Trasporti',
  'Sistemi e infrastrutture per il movimento di persone e merci'),
 ('cucina_alimentazione',
  'Cucina e alimentazione',
  'Preparazione dei cibi, dietetica e cultura gastronomica'),
 ('sport', 'Sport', 'Attività fisiche agonistiche e ricreative regolate'),
 ('vita_quotidiana',
  'Vita quotidiana',
  "Routine, pratiche e aspetti ordinari dell'esistenza"),
 ('competenze_pratiche',
  'Competenze pratiche',
  'Abilità manuali e know-how per la gestione autonoma della vita'),
 ('cultura_digitale',
  'Cultura digitale',
  'Competenze, pratiche e fenomeni della società digitale'),
 ('sicurezza', 'Sicurezza', 'Protezione da rischi, minacce e pericoli per persone e beni'),
 ('cittadinanza',
  'Cittadinanza',
  'Diritti, doveri e partecipazione alla vita collettiva'),
 ('attualita_societa',
  'Attualità e società',
  'Fenomeni, dibattiti e dinamiche del contemporaneo')]
